apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: products-service-deployment
  name: products-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-service
  strategy: {}
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
      - image: andrihurabaquino/products-service-example:latest
        name: products-service-container
