apiVersion: v1
kind: Service
metadata:
  name: products-service-service
spec:
  type: LoadBalancer
  selector:
    app: products-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080