apiVersion: v1
kind: Service
metadata:
  name: shipping-service-service
spec:
  type: LoadBalancer
  selector:
    app: shipping-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080