apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipping-service-deployment
  name: shipping-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  strategy: {}
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - image: andrihurabaquino/shipping-service-example:latest
        name: shipping-service-container
