apiVersion: v1
kind: Pod
metadata:
  labels:
    app: shipping-service
  name: shipping-service
spec:
  containers:
  - name: shipping-service-container
    image: andrihurabaquino/shipping-service-example:latest
  dnsPolicy: ClusterFirst
  restartPolicy: Always