name: CI Build and Deploy

on:
  push:
    branches:
      - main
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Install SonarScanner
        run: npm install -g sonar-scanner

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.java.binaries=target/classes

  build_and_deploy_dockerhub:
    runs-on: ubuntu-latest
    needs: [sonarcloud, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          if [[ ${{ github.ref_name }} == 'main' ]]; then
            docker build . -t ${{ secrets.DOCKER_USERNAME }}/shipping-service-example:latest
          elif [[ ${{ github.ref_name }} == 'release' ]]; then
            docker build . -t ${{ secrets.DOCKER_USERNAME }}/shipping-service-example-release:latest
          elif [[ ${{ github.ref_name }} == 'develop' ]]; then
            docker build . -t ${{ secrets.DOCKER_USERNAME }}/shipping-service-example-develop:latest
          fi

      - name: Push Docker image to Docker Hub
        run: |
          if [[ ${{ github.ref_name }} == 'main' ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/shipping-service-example:latest
          elif [[ ${{ github.ref_name }} == 'release' ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/shipping-service-example-release:latest
          elif [[ ${{ github.ref_name }} == 'develop' ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/shipping-service-example-develop:latest
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy_dockerhub
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          if [[ ${{ github.ref_name }} == 'main' ]]; then
            aws eks update-kubeconfig --name eks-proyectodevops --region ${{ secrets.AWS_REGION }}
          elif [[ ${{ github.ref_name }} == 'release' ]]; then
            aws eks update-kubeconfig --name eks-proyectodevops-release --region ${{ secrets.AWS_REGION }}
          elif [[ ${{ github.ref_name }} == 'develop' ]]; then
            aws eks update-kubeconfig --name eks-proyectodevops-develop --region ${{ secrets.AWS_REGION }}
          fi
      - name: Validate deployment YAML
        run: kubectl apply -f ./shipping-service-deployment.yaml --dry-run=client

      - name: Deploy to Kubernetes
        run: kubectl apply -f ./shipping-service-deployment.yaml

      - name: Deploy Load Balancer Service
        run: kubectl apply -f ./shipping-service-svc.yaml

      - name: Get Load Balancer URL
        id: get_url
        run: |
          echo "Getting the Load Balancer URL..."
          sleep 60
          SERVICE_URL=$(kubectl get svc shipping-service-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "SERVICE_URL=${SERVICE_URL}" >> $GITHUB_ENV
   
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Newman
        run: npm install -g newman

  
      - name: Run Newman tests
        env:
          SERVICE_URL: ${{ env.SERVICE_URL }}
        run: |
          newman run ./Postman/CollectionShipping.postman_collection.json --env-var linkService=${{ env.SERVICE_URL }}
          